---
- name: Check for storage serviceaccount
  command: "/usr/local/bin/oc get serviceaccount provisioner -n kube-system"
  register: user
  failed_when: user.rc > 1
- name: Create storage serviceaccount
  command: /usr/local/bin/oc create serviceaccount provisioner -n kube-system
  when: user.stdout == ""
- name: Grant privileged access to storage serviceaccount
  command: /usr/local/bin/oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:provisioner
- name: Prepare provisioner deployment yaml
  template:
    src: "{{ role_path }}/templates/provisioner.yaml"
    dest: /provisioner.yaml
- name: Apply the provisioner
  command: /usr/local/bin/oc apply -f /provisioner.yaml
