version: "2"
services:
    rabbitmq:
        image: rabbitmq
        ports:
          - "5672:5672"
        hostname: rabbitmq
    mariadb:
        image: mariadb
        hostname: mariadb
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_DATABASE=cinder
          - MYSQL_USER=cinder
          - MYSQL_PASSWORD=password
        ports:
          - 3306:3306
        volumes:
            - ./.data/db_data:/var/lib/mysql
        network_mode: "host"
    cinder-api:
        image: kubevirtci/cinder:ocata
        hostname: cinder-api
        network_mode: "host"
        ports:
            - 8776:8776
        depends_on:
          - mariadb
        environment:
            - INIT_DB=true
        command: sh /scripts/cinder-api.sh
    cinder-scheduler:
        image: kubevirtci/cinder:ocata
        hostname: cinder-scheduler
        depends_on:
          - mariadb
          - rabbitmq
          - cinder-api
        network_mode: "host"
        depends_on:
          - cinder-api
        restart: on-failure
        command: cinder-scheduler
    cinder-volume:
        image: kubevirtci/cinder:ocata
        hostname: cinder-volume
        privileged: true
        volumes:
            - ./.data/ceph:/etc/ceph
        depends_on:
          - cinder-scheduler
          - ceph
        ports:
            - 3260:3260
        network_mode: "host"
        restart: on-failure
        command: bash -c "/scripts/ceph-service.sh"
    ceph:
        image: kubevirtci/ceph:kraken
        hostname: ceph
        privileged: true
        volumes:
            - ./.data/ceph:/etc/ceph
            - ./.data/lib:/var/lib/ceph
        ports:
            - 5000:5000
            - 6789:6789
            - "6800-7300:6800-7300"
        network_mode: "host"
        restart: on-failure
        command: 
          - demo
