version: "2"
services:
    rabbitmq:
        image: rabbitmq
        ports:
          - "5672:5672"
        hostname: rabbitmq
        networks:
            cindernet:
                ipv4_address: 172.49.49.5
    mariadb:
        image: mariadb
        hostname: mariadb
        environment:
          - MYSQL_ROOT_PASSWORD=password
        ports:
          - 3306:3306
        networks:
            cindernet:
                ipv4_address: 172.49.49.6
        volumes:
            - ./.data/db_data:/var/lib/mysql
            - ./scripts/mariadb:/docker-entrypoint-initdb.d
    cinder-api:
        image: rmohr/cinder:ocata
        hostname: cinder-api
        volumes:
            - ./etc:/etc/cinder
            - ./scripts:/scripts
        network_mode: "host"
        ports:
            - 8776:8776
        depends_on:
          - mariadb
        extra_hosts:
            - "rabbitmq:172.49.49.5"
            - "mariadb:172.49.49.6"
        environment:
            - INIT_DB=true
        command: sh /scripts/cinder-api.sh
    cinder-scheduler:
        image: rmohr/cinder:ocata
        hostname: cinder-scheduler
        volumes:
            - ./etc:/etc/cinder
        depends_on:
          - mariadb
          - rabbitmq
          - cinder-api
        extra_hosts:
            - "rabbitmq:172.49.49.5"
            - "mariadb:172.49.49.6"
        network_mode: "host"
        depends_on:
          - cinder-api
        restart: on-failure
        command: cinder-scheduler
    cinder-volume:
        image: rmohr/cinder:ocata
        hostname: cinder-volume
        privileged: true
        volumes:
            - ./ceph:/etc/ceph
            - ./etc:/etc/cinder
            - ./scripts:/scripts
        depends_on:
          - cinder-scheduler
          - ceph
        ports:
            - 3260:3260
        extra_hosts:
            - "rabbitmq:172.49.49.5"
            - "mariadb:172.49.49.6"
        network_mode: "host"
        restart: on-failure
        command: bash -c "/scripts/ceph-service.sh"
    ceph:
        image: ceph/demo:tag-build-master-kraken-centos-7
        hostname: ceph
        privileged: true
        environment:
          - CEPH_DEMO_UID=kubevirt
          - CEPH_DEMO_ACCESS_KEY=kubevirt
          - CEPH_DEMO_SECRET_KEY=kubevirt
          - CEPH_DEMO_BUCKET=kubevirt
          - MON_IP=192.168.178.62
          - CEPH_PUBLIC_NETWORK=0.0.0.0/0
        volumes:
            - ./.data/ceph:/etc/ceph
            - ./.data/lib:/var/lib/ceph
            - ./scripts:/scripts
        ports:
            - 5000:5000
            - 6789:6789
            - "6800-7300:6800-7300"
        network_mode: "host"
        restart: on-failure
        entrypoint: 
          - /scripts/ceph-entrypoint.sh
          - demo

networks:
    cindernet:
        driver: bridge
        ipam:
            driver: default
            config:
            -
              subnet: 172.49.49.0/24
