version: "2"
services:
    ceph:
        image: kubevirtci/ceph:kraken
        hostname: ceph
        privileged: true
        ports:
            - 5000:5000
            - 6789:6789
            - "6800-7300:6800-7300"
        network_mode: "host"
        restart: on-failure
        command: demo
